#NumPy Tutorial for beginners
1. NumPy is used for numerical computation in python
2. NumPy provides ndimensional array objects
3. Array has a fixed size it contain only homogenous datas


This is an introductory numpy tutorial.

In [1]:
# importing numpy
import numpy as np

In [ ]:
# creating a numpy array using np.array() method
numpy_array_1 = np.array((1,3,5,7,9))
print(numpy_array_1)
print(f'type of numpy_array_1 is {type(numpy_array_1)}')

[1 3 5 7 9]
type of numpy_array_1 is <class 'numpy.ndarray'>


In [ ]:
# converting a list into a numpy array
my_list = [x for x in range(11) if x % 2 == 0 ]
print(my_list)
list_to_numpyarray = np.array(my_list)
print(type(list_to_numpyarray))

[0, 2, 4, 6, 8, 10]
<class 'numpy.ndarray'>


1. vector: 1 dimensional array
2. matrix: 2 dimensional array
3. tensor: 3 or higher dimensional arrays

in numpy dimensions are called axes

# creating different types of arrays using numpy
1. np,array()
2. np.zeros()
3. np.ones()
4. np.arange(start, end, step size)

In [21]:
np_zero_array = np.zeros((5)) # creating an array filled with zeros it has five elements
#print(np_zero_array)
np_zero_array

array([0., 0., 0., 0., 0.])

In [ ]:
print(np.zeros((3,3),dtype = int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
np_ones_array = np.ones(4) # creating an array filled with ones and it has four elements
print(np_ones_array)

[1. 1. 1. 1.]


In [ ]:
print(np.ones((3,3),dtype = int))


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
np_range_array = np.arange(1,11,2)
print(np_range_array)

[1 3 5 7 9]


In [22]:
arr = np.arange(1,21).reshape(5,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
# one dimensional array
oned_array = np.array([1,2,3,4,5])
print(oned_array)
print(oned_array.shape)

[1 2 3 4 5]
(5,)


In [ ]:
# 2D array
twod_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twod_array)
print(twod_array.shape) # 3,3 means first axis has 3 elements and second axis has 3 elements

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
# 3D array
threed_array = np.array([[[1, 2, 3], [4, 5, 6],[7,8,9]], [[1, 2, 3], [4, 5, 6],[11,12,13]]])
print(threed_array)
print(threed_array.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1  2  3]
  [ 4  5  6]
  [11 12 13]]]
(2, 3, 3)


By default data type in numpy is floating point(float64) by using dtype keyword we can specify the data type

In [ ]:
x = np.ones(4)
print(x)
y = np.ones(4, dtype = np.int64)
print(y)

[1. 1. 1. 1.]
[1 1 1 1]


In [ ]:
# sorting of an array
np_array_1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(np_array_1)) # np.sort() method is used to sort the array

[1 2 3 4 5 6 7 8]


In [ ]:
# concatenating arrays

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.concatenate([a,b])
print(c)

[1 2 3 4 5 6 7 8]


1. axis = 0 refers to the vertical axis or the rows, it means you want to concatenate arrays vertically/ along the rows. stacking them on top of each other.
2. axis = 1 refers to the horizontal axis ot the columns, it means youb want to concatenate the arrays horizontally/ along the columns. horizontally extend pr append one array to another.

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

z = np.concatenate([x,y], axis = 0)
print(z)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
q = np.concatenate((x,y),axis = 1)
print(q)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# ndim: tell number of axes pr dimension in the array
# size: tell the total number of elements
# shape : retruns a tuple of integers that indicate the number of elements stored along each dimension of the array.

sample_array1 = np.array([1,2,3,4])
print("Dimension of the array:",sample_array1.ndim)
print("Size of the array:", sample_array1.size)
print("Shape of the array:",sample_array1.shape)
sample_array2 = np.array([[1,2],[3,4],[5,6]])
print("Dimension of the array:",sample_array2.ndim)
print("Size of the array:",sample_array2.size)
print("Shape of the array:",sample_array2.shape)

Dimension of the array: 1
Size of the array: 4
Shape of the array: (4,)
Dimension of the array: 2
Size of the array: 6
Shape of the array: (3, 2)


1. reshaping an existing array
2. reshape()
3. total number of elements in the original array must be equal to the total number of elements in the newshape.

In [ ]:
x = np.arange(1,21)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# reshaping x
x_reshape = x.reshape(5,4)
print(x_reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]



# indexing and slicing an array

In [ ]:
np_array = np.array([1,2,3,4,5,6])
print(np_array)
print(np_array[0])
print(np_array[1])
print(np_array[2])
print(np_array[3])
print(np_array[4])
print(np_array[5])

[1 2 3 4 5 6]
1
2
3
4
5
6


In [ ]:
print(np_array)
print("total length of the array:",len(np_array))
print(np_array[-1])
print(np_array[-2])
print(np_array[-3])
print(np_array[-4])
print(np_array[-5])
print(np_array[-6])

[1 2 3 4 5 6]
total length of the array: 6
6
5
4
3
2
1


In [ ]:
print(np_array)
print(np_array[1:3])
print(np_array[2:])
print(np_array[:4])
print(np_array[::2])
print(np_array[:])
print(np_array[-3:-1])

[1 2 3 4 5 6]
[2 3]
[3 4 5 6]
[1 2 3 4]
[1 3 5]
[1 2 3 4 5 6]
[4 5]


In [ ]:
twod_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twod_array)
print(twod_array[0])
print(twod_array[1])
print(twod_array[2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
print(twod_array[:,:])
print(twod_array[:,:2])
print(twod_array[1:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[5 6]
 [8 9]]


In [ ]:
import random
array1 = np.random.randint(20, size = (4,3))
print(array1)
print("Dimension of the array:",array1.ndim)
print("Shape of the array:", array1.shape)

[[ 9 17  1]
 [16  5 11]
 [ 0 17 15]
 [19  6 16]]
Dimension of the array: 2
Shape of the array: (4, 3)


In [ ]:
print(array1[:])

[[ 9 17  1]
 [16  5 11]
 [ 0 17 15]
 [19  6 16]]


In [ ]:
print(array1[::])

[[ 9 17  1]
 [16  5 11]
 [ 0 17 15]
 [19  6 16]]


In [ ]:
print(array1[1:])

[[16  5 11]
 [ 0 17 15]
 [19  6 16]]


In [ ]:
print(array1[:3])

[[ 9 17  1]
 [16  5 11]
 [ 0 17 15]]


In [ ]:
print(array1[1:3])

[[16  5 11]
 [ 0 17 15]]


In [ ]:
print(array1[0,0])
print(array1[0,2])
print(array1[1,1])

9
1
5


In [ ]:
print(array1[:,1:]) # including all the rows but axclusding the first column

[[17  1]
 [ 5 11]
 [17 15]
 [ 6 16]]


In [ ]:
print(array1[:,:2])

[[ 9 17]
 [16  5]
 [ 0 17]
 [19  6]]


In [ ]:
print("Highest value:",array1.max())
print("Smallest Value:",array1.min())
print("Sum:",array1.sum())

Highest value: 19
Smallest Value: 0
Sum: 132


In [ ]:
print(array1.max(axis = 0)) # print highest value along the axis equals to zero(vertically)

[19 17 16]


In [ ]:
print(np.ones((2,3),dtype = int)) # creating 2D Array using np.ones()

[[1 1 1]
 [1 1 1]]


In [ ]:
print(np.zeros((3,4),dtype = int))  # creating 2D Array using np.zeros()

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
print(np.random.rand(3,3))

[[0.40957293 0.09882964 0.84276736]
 [0.56357073 0.22379075 0.49763402]
 [0.5818829  0.0658579  0.669765  ]]


1. a < 5: This part creates a Boolean mask.
2. It checks each element of the array a to see if it is less than 5.
3. If an element is less than 5, it assigns True, otherwise False.
4. This results in a new array of the same shape as a with True and False values indicating which elements meet the condition:
5. a[a < 5]: Now, we use this Boolean mask as an index to select elements from the original array a.
6. It picks only the elements from a where the corresponding value in the Boolean mask is True.
7. In our case, it selects the elements [1, 2, 3, 4] because those are the elements in a where the condition a < 5 is True.

In [ ]:
a = np.array([x for x in range(11)])
print(a)
print(a[a < 5])
print(a[a>=5])
divisibleby_2 = a % 2 == 0
print(divisibleby_2)
print(a[divisibleby_2])

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[ 5  6  7  8  9 10]
[ True False  True False  True False  True False  True False  True]
[ 0  2  4  6  8 10]


1. When we do vertical stack column size must be same, row size can be vary.
2. when we do horizontal stack row size must be equal, column size can vary.


In [ ]:
import random
x = np.random.randint(5,size = (2,3))
print(x)
print("-----------------------------")
y = np.random.randint(5,size = (5,3))
print(y)
print("------------------------------")
z = np.vstack((x,y))
print(z)

[[2 4 4]
 [3 3 4]]
-----------------------------
[[3 4 2]
 [1 1 0]
 [2 4 0]
 [1 4 0]
 [4 2 2]]
------------------------------
[[2 4 4]
 [3 3 4]
 [3 4 2]
 [1 1 0]
 [2 4 0]
 [1 4 0]
 [4 2 2]]


Showing an error messgae(ValueError) because columns size of both arrays are different. column size must be equal when we do vstack.

In [ ]:
a = np.random.randint(10,size = (5,3))
print(a)
print("-------------------------")
b = np.random.randint(6, size = (3,4))
print(b)
print("-------------------------")

c = np.vstack((a,b))
print(c)

[[6 7 9]
 [6 7 3]
 [8 9 2]
 [4 3 4]
 [8 2 1]]
-------------------------
[[0 1 5 0]
 [5 4 0 2]
 [4 3 0 2]]
-------------------------


ValueError: ignored

In [ ]:
x = np.random.randint(10, size = (5,3))
print(x)
print("-----------------------------")
y = np.random.randint(7, size = (5,4))
print(y)
print("-----------------------------")

z = np.hstack((x,y))
print(z)

[[9 7 6]
 [5 6 9]
 [2 4 2]
 [2 4 8]
 [6 5 2]]
-----------------------------
[[0 4 3 5]
 [3 3 4 2]
 [1 2 4 5]
 [0 3 1 4]
 [6 5 5 0]]
-----------------------------
[[9 7 6 0 4 3 5]
 [5 6 9 3 3 4 2]
 [2 4 2 1 2 4 5]
 [2 4 8 0 3 1 4]
 [6 5 2 6 5 5 0]]


Showing an error messgae(ValueError) because row size of both arrays are different. row size must be equal when we do hstack.

In [ ]:
x = np.random.randint(10, size = (5,3))
print(x)
print("-----------------------------")
y = np.random.randint(7, size = (2,4))
print(y)
print("-----------------------------")

z = np.hstack((x,y))
print(z)

[[6 1 6]
 [9 6 4]
 [6 2 3]
 [2 6 4]
 [8 0 6]]
-----------------------------
[[4 1 5 4]
 [6 2 4 0]]
-----------------------------


ValueError: ignored

# Array operations

In [ ]:
x = np.random.randint(10, size = (3))
print(x)
print("--------------")

y = np.random.randint(20,size = (3))
print(y)
print("--------------")

sum = x + y
print(sum)

[6 9 0]
--------------
[ 6  9 16]
--------------
[12 18 16]


In [ ]:
x = np.random.randint(10, size = (3,3))
print(x)
print("--------------")

y = np.random.randint(30,size = (3,3))
print(y)
print("----------------")

print(x + y)

[[3 0 4]
 [7 8 5]
 [7 4 3]]
--------------
[[21 24  3]
 [ 8  4 24]
 [11 25 29]]
----------------
[[24 24  7]
 [15 12 29]
 [18 29 32]]


In [ ]:
x = np.random.randint(10, size = (3))
print(x)
print("--------------")

y = np.random.randint(20,size = (3))
print(y)
print("--------------")

sub = x - y
print(sub)

[6 8 2]
--------------
[15 14  1]
--------------
[-9 -6  1]


In [ ]:
x = np.random.randint(10, size = (3,3))
print(x)
print("--------------")

y = np.random.randint(30,size = (3,3))
print(y)
print("----------------")

print(x - y)

[[7 8 6]
 [8 5 0]
 [2 6 2]]
--------------
[[10 17 18]
 [ 0 14 13]
 [ 3  8  2]]
----------------
[[ -3  -9 -12]
 [  8  -9 -13]
 [ -1  -2   0]]


In [ ]:
x = np.random.randint(10, size = (3))
print(x)
print("--------------")

y = np.random.randint(20,size = (3))
print(y)
print("--------------")

mul = x * y
print(mul)

[9 7 4]
--------------
[16 17 17]
--------------
[144 119  68]


In [ ]:
x = np.random.randint(10, size = (3,3))
print(x)
print("--------------")

y = np.random.randint(30,size = (3,3))
print(y)
print("----------------")

print(x * y)

[[7 9 1]
 [8 9 5]
 [3 5 9]]
--------------
[[ 4 28 16]
 [25 11 14]
 [11  8 17]]
----------------
[[ 28 252  16]
 [200  99  70]
 [ 33  40 153]]


In [ ]:
x = np.random.randint(10, size = (3))
print(x)
print("--------------")

y = np.random.randint(20,size = (3))
print(y)
print("--------------")

div = x / y
print(div)

[2 0 6]
--------------
[10 16  8]
--------------
[0.2  0.   0.75]


In [ ]:
x = np.random.randint(10, size = (3,3))
print(x)
print("--------------")

y = np.random.randint(30,size = (3,3))
print(y)
print("----------------")

print(x / y)

[[2 0 4]
 [2 1 9]
 [1 0 9]]
--------------
[[ 4  4 16]
 [29 23  6]
 [ 6 29 23]]
----------------
[[0.5        0.         0.25      ]
 [0.06896552 0.04347826 1.5       ]
 [0.16666667 0.         0.39130435]]


In [ ]:
x = np.random.randint(10, size = (4))
print(x)
print(f"Sum of the elements in the array  is {x.sum()}")

[9 8 2 9]
Sum of the elements in the array  is 28


In [ ]:
y = np.random.randint(10,size = (3,4))
print(y)
print(f'Sum of the elements in the array is {y.sum()}')

[[3 1 6 2]
 [2 3 5 9]
 [1 1 4 7]]
Sum of the elements in the array is 44


To add the rows or the columns in a 2D array, you would specify the axis.

In [ ]:
# sum over the axis of rows with:
y = np.random.randint(10,size = (3,4))
print(y)
print(f'Sum of the elements in the array is {y.sum(axis = 0)}')

[[5 3 8 1]
 [7 7 3 3]
 [5 8 9 1]]
Sum of the elements in the array is [17 18 20  5]


In [ ]:
# sum over the axis of columns with:
y = np.random.randint(10,size = (3,4))
print(y)
print(f'Sum of the elements in the array is {y.sum(axis = 1)}')

[[5 5 1 0]
 [0 9 8 2]
 [4 9 7 7]]
Sum of the elements in the array is [11 19 27]


In [ ]:
# min() and max()

x = np.random.randint(20, size = (5))
print(x)
print(x.min())
print(x.max())
print(x.sum())

[ 2 13 18  0 15]
0
18
48


In [ ]:
x = np.random.randint(20, size = (5,3))
print(x)


[[ 1 13  2]
 [14 14 17]
 [ 0 18  8]
 [13  0 10]
 [10 18 17]]


In [ ]:
print(x.min()) # print the lowest value in the entire array
print(x.max()) # print the highest value in the entire array
print(x.sum()) # print the sum of each element in the array

0
18
155


In [ ]:
print(x.min(axis = 0)) # print the lowest value in each column/ vertical
print(x.max(axis = 0)) # print the highest value in each column/ vertical
print(x.sum(axis = 0))

[0 0 2]
[14 18 17]
[38 63 54]


In [ ]:
print(x.min(axis = 1)) # print the lowest value in each row/ horizontal
print(x.max(axis = 1)) # print the highest value in each row/ horizontal
print(x.sum(axis = 1))

[ 1 14  0  0 10]
[13 17 18 13 18]
[16 45 26 23 45]


#Creating matrices

In [24]:
import random
array_1 = np.random.rand(3,3)
print(array_1)

[[0.69377437 0.20348443 0.70137844]
 [0.74392867 0.9973091  0.9795146 ]
 [0.21849403 0.74675434 0.9892934 ]]


 # Broadcasting
 Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. If the dimensions are not compatible, you will get a ValueError.

# General Broadcasting Rules
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when
1. they are equal, or
2. one of them is 1.

In [25]:
data = np.array([1,2,3,4])
b = 5
c = data * b
print(c)

[ 5 10 15 20]


In [32]:
data1 = np.random.randint(10, size = (3,1))
print(data1)

data2 = np.random.randint(20,size = (3,3))
print(data2)
print(data1 * data2)


[[1]
 [2]
 [5]]
[[ 0 15 11]
 [ 8 16 10]
 [17  8  1]]
[[ 0 15 11]
 [16 32 20]
 [85 40  5]]


In [36]:
arr1 = np.random.randint(10, size = (4))
print(arr1)
print("---------------------------------")
arr2 = np.random.randint(20,size = (3,4))
print(arr2)
print("---------------------------------")
print(arr1 + arr2)

[0 4 7 6]
---------------------------------
[[ 5  0  9  1]
 [18 12 15  2]
 [14  2  7 11]]
---------------------------------
[[ 5  4 16  7]
 [18 16 22  8]
 [14  6 14 17]]


In [38]:
arr1 = np.random.randint(10, size = (3,4))
print(arr1)
print("---------------------------------")
arr2 = np.random.randint(20,size = (3,4))
print(arr2)
print("---------------------------------")
print(arr1 * arr2)

[[8 9 7 8]
 [3 3 2 0]
 [6 5 2 5]]
---------------------------------
[[18  7 16  2]
 [ 1 10 16  0]
 [17 18  4  6]]
---------------------------------
[[144  63 112  16]
 [  3  30  32   0]
 [102  90   8  30]]


In [37]:
arr1 = np.random.randint(10, size = (5))
print(arr1)
print("---------------------------------")
arr2 = np.random.randint(20,size = (3,4))
print(arr2)
print("---------------------------------")
print(arr1 + arr2)

[5 1 8 6 6]
---------------------------------
[[15  3 10 11]
 [ 1  3  3  3]
 [13  1  2 14]]
---------------------------------


ValueError: ignored

Generating random numbers

In [39]:
print(np.random.randint(100))

74


In [40]:
print(np.random.rand())

0.2383677196414784


In [44]:
# generating random array
# 1D Array
x = np.random.randint(100, size = (4))
print(x)
print("------------------------------")

#2D Array
y = np.random.randint(20, size = (3,4))
print(y)
print("------------------------------")

#3D Array
z = np.random.randint(20,size = (2,3,4))
print(z)

[36 32 60 15]
------------------------------
[[19 13 13 14]
 [12  0  6 15]
 [ 1  0  1 14]]
------------------------------
[[[ 2 19  6 19]
  [19 17 16 19]
  [ 4  4  2 18]]

 [[ 1 12  6  0]
  [16  7  6  6]
  [10 16  5  0]]]


In [47]:
# 1D Array
q = np.random.rand(3)
print(q)
print("-------------------------")
#2D Array
w = np.random.rand(3,5)
print(w)
print("-------------------------")
#3D Array
e = np.random.rand(3,3,4)
print(e)

[0.62848095 0.08728559 0.2909885 ]
-------------------------
[[0.09313346 0.22372729 0.07883358 0.27298593 0.99124076]
 [0.59111799 0.95375714 0.53266524 0.96590045 0.10130547]
 [0.65697861 0.09226971 0.31062409 0.48943708 0.96090923]]
-------------------------
[[[0.93378228 0.29502154 0.86660115 0.08223242]
  [0.6563761  0.00867113 0.24448676 0.06538938]
  [0.79520493 0.13139408 0.12839066 0.69369759]]

 [[0.96091697 0.6466432  0.07366846 0.11967963]
  [0.47552764 0.04846017 0.26504915 0.14942459]
  [0.12488102 0.14871406 0.48317909 0.69089345]]

 [[0.45549034 0.11368008 0.24454633 0.28768374]
  [0.46745343 0.23306913 0.71851962 0.00341599]
  [0.55993286 0.47398309 0.93946599 0.00320335]]]


# unique values


In [49]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(a)
print("------------------")
unique_values = np.unique(a)
print(unique_values)

[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
------------------
[11 12 13 14 15 16 17 18 19 20]



# The transpose of a matrix
The transpose of a matrix is an operation that flips the matrix over its diagonal, effectively swapping its rows and columns. If you have a matrix A, denoted as A^T, the transpose of A is obtained by making the rows of A become the columns of A^T and vice versa.

In [54]:
x = np.arange(30).reshape(5,6)
print(x)
print("----------------------")
print("Transpose of the matrix 'x'")
print(x.transpose()) # use .transpose() or .T()

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
----------------------
Transpose of the matrix 'x'
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [58]:
y = np.arange(20).reshape(4,5)
print(y)
print("----------------------")
print("Transpose of the matrix \'y\'")
print(y.T)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
----------------------
Transpose of the matrix 'y'
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


#The Difference Between Copy and View
1. The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

2. The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

3. The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [63]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
print(f"This is the original array: {arr}")
print(f"This is the copy of \'arr\': {x}")

This is the original array: [1 2 3 4 5]
This is the copy of 'arr': [1 2 3 4 5]


In [65]:
x[0] = 234
print(arr)
print(x)

[1 2 3 4 5]
[234   2   3   4   5]


In [66]:
arr[3] =345
print(x)
print(arr)

[234   2   3   4   5]
[  1   2   3 345   5]


In [67]:
arr = np.array([1, 2, 3, 4, 5])
y = arr.view()
print(f"This is the original array: {arr}")
print(f"This is the view of \'arr\': {y}")

This is the original array: [1 2 3 4 5]
This is the view of 'arr': [1 2 3 4 5]


In [68]:
arr[3] = 100
print(arr)
print(y)

[  1   2   3 100   5]
[  1   2   3 100   5]


In [69]:
y[1] = 34
print(arr)
print(y)

[  1  34   3 100   5]
[  1  34   3 100   5]
